#! /usr/bin/env perl


=head1 DESCRIPTION

hitman_execute performs OTU clustering, taxonomic assignment and rarefaction on
the input cleaned and trimmed FASTA sequences to produce a BIOM file.

=head1 MANDATORY ARGUMENTS

=over

=item -i <seqs> | --input <seqs>

Input FASTA file containing the cleaned, trimmed sequences from the previous
hitman_deploy step. The file must have a *.fna extension.

=for Euclid:
   seqs.type: readable

=item -q <primers> | --primers <primers>

Input FASTA file containing the two PCR primers used, following the IUPAC
convention for degenerate residues. The primers need not be in a specific order,
but the file must have a *.fna extension.

=for Euclid:
   primers.type: readable

=back

=cut


use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/../lib";
use Hitman;

Hitman::parse_args();
my $inputs = [ $ARGV{'--input'}, $ARGV{'--primers'} ];
Hitman::run_hitman( $inputs );

exit;

