#! /usr/bin/env perl


=head1 DESCRIPTION

hitman_execute performs OTU clustering, taxonomic assignment and rarefaction on
the input cleaned and trimmed FASTA sequences to produce a BIOM file.

=head1 MANDATORY ARGUMENTS

=over

=item -s <seqs> | --seqs <seqs>

Input FASTA file containing the cleaned, trimmed sequences from the previous
hitman_deploy step. The file must have a *.fna extension.

=for Euclid:
   seqs.type: readable

=item -q <primers> | --primers <primers>

Input FASTA file containing the two PCR primers used, following the IUPAC
convention for degenerate residues. The forward primer used for sequencing
must be named 'fwd', the reverse 'rev'. The file must have a *.fna extension.

=for Euclid:
   primers.type: readable

=back

=cut


use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/../lib";
use Hitman;

Hitman::parse_args();
my $inputs = [ $ARGV{'--seqs'}, $ARGV{'--primers'} ];
Hitman::run( $inputs );

exit;

